// Copyright (c) 2024 Tencent. All rights reserved.
#ifndef SUPERPLAYER_FLUTTER_IOS_CLASSES_COMMON_FTXPLAYERCONSTANTS_H_
#define SUPERPLAYER_FLUTTER_IOS_CLASSES_COMMON_FTXPLAYERCONSTANTS_H_

#import "FTXLiteAVSDKHeader.h"

#define ADJUST_RESOLUTION 0
#define FULL_FILL_CONTAINER 1
#define SCALE_FULL_FILL_CONTAINER 2

#endif  // SUPERPLAYER_FLUTTER_IOS_CLASSES_COMMON_FTXPLAYERCONSTANTS_H_
